---
title: Tidy data for analysis for STA5069Z course
format:
  html:
    embed-resources: true
---

# Introduction

```{r}
#| include: false
library(tibble)
```


## MDS

### Morse code data

```{r}
data_raw_morse <- readr::read_csv(
  projr::projr_path_get("data-raw", "morse.code.csv")
)
data_tidy_morse <- data_raw_morse
projr::projr_use_data(data_tidy_morse, overwrite = TRUE)
```

### SA distance data

```{r}
data_raw_sa_distance <- openxlsx::read.xlsx(
  projr::projr_path_get("data-raw", "SAdistances.xlsx"),
  sheet = 2
) |>
  tibble::as_tibble()
data_tidy_sa_distance <- data_raw_sa_distance
colnames(data_tidy_sa_distance)[which(colnames(data_tidy_sa_distance) == "CapeTOwn")] <- "CapeTown"
projr::projr_use_data(data_tidy_sa_distance, overwrite = TRUE)
```

## Cluster analysis

### Food

```{r}
data_raw_food <- readr::read_table(
  projr::projr_path_get("data-raw", "food.txt")
)
data_tidy_food <- data_raw_food
ugly_to_display_vec <- ugly_to_display_vec <- c(
  "\"Fat.grams\"" = "fat_grams",
  "\"Food.energy.calories\"" = "food_energy_calories",
  "\"Carbohydrates.grams\"" = "carbohydrates_grams",
  "\"Protein.grams\"" = "protein_grams",
  "\"Cholesterol.mg\"" = "cholesterol_mg",
  "\"weight.grams\"" = "weight_grams",
  "\"Saturated.fat.grams\"" = "saturated_fat_grams",
  "\"cluster.id\"" = "cluster_id",
  "\"Fat2.grams\"" = "fat2_grams",
  "\"Food.energy2.calories\"" = "food_energy2_calories",
  "\"Carbohydrates2.grams\"" = "carbohydrates2_grams",
  "\"Protein2.grams\"" = "protein2_grams",
  "\"Cholesterol2.mg\"" = "cholesterol2_mg",
  "\"Saturated.fat2.grams\"" = "saturated_fat2_grams"
)
colnames(data_tidy_food) <- ugly_to_display_vec[colnames(data_tidy_food)]
projr::projr_use_data(data_tidy_food, overwrite = TRUE)
```

## Example 12.3.4

```{r}
data_raw_example_12_3_4 <- readr::read_csv(
  projr::projr_path_get("data-raw", "Ex12.3.4.csv")
)
data_tidy_example_12_3_4 <- data_raw_example_12_3_4
projr::projr_use_data(data_tidy_example_12_3_4, overwrite = TRUE)
```

## Primate scapulae

```{r}
data_raw_primate <- readr::read_csv(
  projr::projr_path_get("data-raw", "primate.scapulae.csv")
)
data_tidy_primate <- data_raw_primate |>
  dplyr::rename(
    genus = "genus",
    AD_BD = "AD.BD",
    AD_CD = "AD.CD",
    EA_CD = "EA.CD",
    Dx_CD = "Dx.CD",
    SH_ACR = "SH.ACR",
    EAD = "EAD",
    beta = "beta",
    gamma = "gamma",
    class = "class",
    classdigit = "classdigit"
  )
projr::projr_use_data(data_tidy_primate, overwrite = TRUE)
```

## Satellite images

```{r}
data_raw_satellite <- readr::read_table(
  projr::projr_path_get("data-raw", "satimage.txt")
)
data_tidy_satellite <- data_raw_satellite
colnames(data_tidy_satellite) <- gsub("\"", "", colnames(data_tidy_satellite))
projr::projr_use_data(data_tidy_satellite, overwrite = TRUE)
```

## T11-5

```{r}
data_raw_t11_5 <- readr::read_table(
  projr::projr_path_get("data-raw", "T11-5.DAT"),
  col_names = FALSE
)
data_tidy_t11_5 <- data_raw_t11_5
projr::projr_use_data(data_tidy_t11_5, overwrite = TRUE)
```
